title:   Tai Fu
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a Job Seeker based in Toronto, with working experience on both Data Analytics and Business Intelligence tasks in retail and consultant industries. 
  <br><br>
  Perceptive and logical professional with proven ability to communicate with both technical professionals and end users to identify and translate business requirements. Proven ability to work with talented professionals to develop valuable process solutions to meet business objectives.
  <br><br>
  <a href="https://public.tableau.com/app/profile/tai.fu">View My Tableau Public</a>
  <br><br>
  <a href="https://empfu.notion.site/About-Me-Tai-Fu-b583b7b202844dc4a39fc7fcb913cb1c">View My Notion Portfolios</a>


theme: jekyll-theme-minimal
