title:   Tai Fu
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a seasoned Toronto-based data analyst with strong background of sales, finance, and people skills, passionate about bringing valuable insights to drive business changes.
  <br><br>
  Skills: <br> MS Excel, MS Access, Power BI, Tableau, SQL, Python, Google Analytics
  <br><br>
  <a href="https://public.tableau.com/app/profile/tai.fu">View My Tableau Public</a>
  <br><br>
  <a href="https://github.com/empfudata/Projects">View My GitHub Projects</a>

# <br><br>
# <a href="https://empfu.notion.site/About-Me-Tai-Fu-b583b7b202844dc4a39fc7fcb913cb1c">View My Notion Portfolios</a>


theme: jekyll-theme-minimal
